---
- name: Configure web server
  hosts: webservers
  become: yes
  vars_files:
    - vars/main.yml
  roles:
    - web

- name: Configure database server
  hosts: dbservers
  become: yes
  vars_files:
    - vars/main.yml
  roles:
    - db